   m # infrastructure/values.yaml
global:
  domain: unbund.com
  cloudflare:
    tunnelId: "22051e43-bc84-438d-b7c3-b829c1e2f6ad"
    tunnelTarget: "22051e43-bc84-438d-b7c3-b829c1e2f6ad.cfargotunnel.com"

# Shared settings for components
ingress-nginx:
  controller:
    service:
      type: ClusterIP

external-dns:
  provider: cloudflare
  domainFilters: ["unbund.com"]
